site_name: Workflow Core
nav:
    - Home: index.md
    - Getting started: geting-started.md
    - External events: external-events.md
    - Error handing: error-handling.md
    - Control structures: control-structures.md
    - Saga transactions: sagas.md
    - JSON / YAML Definitions: json-yaml.md
    - Persistence: persistence.md
    - Multi-node clusters: multi-node-clusters.md
    - ASP.NET Core.md: using-with-aspnet-core.md
    - Extensions: extensions.md
    - Samples: samples.md
theme: readthedocs